
-- CodeFun v1.0 - gestión académica
-- Ejecutar completo en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  control_number text,
  username text,
  role text not null default 'student' check (role in ('student','teacher','admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists username text;

create unique index if not exists profiles_username_lower_idx
  on public.profiles (lower(username)) where username is not null;

-- Gamificación: racha de días consecutivos practicando.
alter table public.profiles add column if not exists streak_current integer not null default 0;
alter table public.profiles add column if not exists streak_best integer not null default 0;
alter table public.profiles add column if not exists streak_last_date date;

create table if not exists public.school_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  code text not null unique,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  school_year text,
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  group_id uuid not null references public.school_groups(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key(group_id, student_id)
);

create table if not exists public.exercise_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  exercise_id text not null,
  subject_id text not null,
  topic text not null,
  answer text,
  correct boolean not null,
  xp integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.student_progress (
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id text not null,
  exercises_done integer not null default 0,
  correct_answers integer not null default 0,
  xp integer not null default 0,
  last_activity timestamptz,
  updated_at timestamptz not null default now(),
  primary key(student_id, subject_id)
);

-- Perfil automático al registrarse.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles(id, full_name, control_number, username, role)
  values(
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name',''),
    nullif(new.raw_user_meta_data ->> 'control_number',''),
    nullif(new.raw_user_meta_data ->> 'username',''),
    'student'
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Unirse a un grupo usando su código.
create or replace function public.join_group_by_code(p_code text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare v_group uuid;
begin
  select id into v_group
  from public.school_groups
  where upper(code)=upper(trim(p_code));

  if v_group is null then
    raise exception 'Código de grupo no válido';
  end if;

  insert into public.group_members(group_id,student_id)
  values(v_group,auth.uid())
  on conflict do nothing;

  return v_group;
end;
$$;

-- Registrar intento y actualizar resumen del estudiante.
create or replace function public.record_attempt(
  p_exercise_id text,
  p_subject_id text,
  p_topic text,
  p_answer text,
  p_correct boolean,
  p_xp integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.exercise_attempts(student_id,exercise_id,subject_id,topic,answer,correct,xp)
  values(auth.uid(),p_exercise_id,p_subject_id,p_topic,p_answer,p_correct,p_xp);

  insert into public.student_progress(student_id,subject_id,exercises_done,correct_answers,xp,last_activity)
  values(auth.uid(),p_subject_id,1,case when p_correct then 1 else 0 end,p_xp,now())
  on conflict(student_id,subject_id) do update
  set exercises_done=student_progress.exercises_done+1,
      correct_answers=student_progress.correct_answers+case when excluded.correct_answers=1 then 1 else 0 end,
      xp=student_progress.xp+excluded.xp,
      last_activity=now(),
      updated_at=now();

  update public.profiles
  set streak_current = case
        when streak_last_date = current_date then streak_current
        when streak_last_date = current_date - 1 then streak_current + 1
        else 1
      end,
      streak_best = greatest(streak_best, case
        when streak_last_date = current_date then streak_current
        when streak_last_date = current_date - 1 then streak_current + 1
        else 1
      end),
      streak_last_date = current_date
  where id = auth.uid();
end;
$$;

-- Helper functions (security definer = bypass RLS internally) to avoid
-- infinite recursion between the school_groups and group_members policies,
-- since each one otherwise needs to read the other RLS-protected table.
create or replace function public.is_teacher_of_group(p_group_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists(
    select 1 from public.school_groups sg
    where sg.id = p_group_id and sg.teacher_id = auth.uid()
  );
$$;

create or replace function public.is_member_of_group(p_group_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists(
    select 1 from public.group_members gm
    where gm.group_id = p_group_id and gm.student_id = auth.uid()
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

-- Solo un admin puede cambiar el rol de una cuenta (evita que un alumno se
-- autoasigne role='teacher'/'admin' vía un update directo a su propio perfil).
create or replace function public.prevent_self_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Solo se restringe cuando la escritura llega vía PostgREST como un
  -- usuario autenticado normal. Conexiones directas (SQL Editor, CLI,
  -- service_role) no pasan por aquí, para poder crear el primer admin.
  if new.role is distinct from old.role and auth.role()='authenticated' and not public.is_admin() then
    raise exception 'Solo un administrador puede cambiar el rol de una cuenta.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_self_role_change on public.profiles;
create trigger trg_prevent_self_role_change
before update on public.profiles
for each row execute procedure public.prevent_self_role_change();

-- RLS
alter table public.profiles enable row level security;
alter table public.school_groups enable row level security;
alter table public.group_members enable row level security;
alter table public.exercise_attempts enable row level security;
alter table public.student_progress enable row level security;

drop policy if exists "profile own read" on public.profiles;
create policy "profile own read" on public.profiles for select to authenticated
using (id=auth.uid());

drop policy if exists "profile own update" on public.profiles;
create policy "profile own update" on public.profiles for update to authenticated
using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists "teachers see group students" on public.profiles;
create policy "teachers see group students" on public.profiles for select to authenticated
using (
  exists(
    select 1
    from public.group_members gm
    join public.school_groups sg on sg.id=gm.group_id
    where gm.student_id=profiles.id and sg.teacher_id=auth.uid()
  )
);

drop policy if exists "teacher groups read" on public.school_groups;
create policy "teacher groups read" on public.school_groups for select to authenticated
using (teacher_id=auth.uid() or public.is_member_of_group(id));

drop policy if exists "teacher groups insert" on public.school_groups;
create policy "teacher groups insert" on public.school_groups for insert to authenticated
with check (
  teacher_id=auth.uid() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('teacher','admin'))
);

drop policy if exists "teacher groups update" on public.school_groups;
create policy "teacher groups update" on public.school_groups for update to authenticated
using (teacher_id=auth.uid()) with check (teacher_id=auth.uid());

drop policy if exists "members relevant read" on public.group_members;
create policy "members relevant read" on public.group_members for select to authenticated
using (
  student_id=auth.uid() or public.is_teacher_of_group(group_id)
);

drop policy if exists "student own attempts" on public.exercise_attempts;
create policy "student own attempts" on public.exercise_attempts for select to authenticated
using (student_id=auth.uid());

drop policy if exists "teacher group attempts" on public.exercise_attempts;
create policy "teacher group attempts" on public.exercise_attempts for select to authenticated
using (
  exists(
    select 1 from public.group_members gm
    join public.school_groups sg on sg.id=gm.group_id
    where gm.student_id=exercise_attempts.student_id and sg.teacher_id=auth.uid()
  )
);

drop policy if exists "student own progress" on public.student_progress;
create policy "student own progress" on public.student_progress for select to authenticated
using (student_id=auth.uid());

drop policy if exists "teacher group progress" on public.student_progress;
create policy "teacher group progress" on public.student_progress for select to authenticated
using (
  exists(
    select 1 from public.group_members gm
    join public.school_groups sg on sg.id=gm.group_id
    where gm.student_id=student_progress.student_id and sg.teacher_id=auth.uid()
  )
);

-- Admin: acceso total para ver y administrar todas las cuentas, grupos y avance.
drop policy if exists "admin all profiles" on public.profiles;
create policy "admin all profiles" on public.profiles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin all groups" on public.school_groups;
create policy "admin all groups" on public.school_groups for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin all members" on public.group_members;
create policy "admin all members" on public.group_members for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin read attempts" on public.exercise_attempts;
create policy "admin read attempts" on public.exercise_attempts for select to authenticated
using (public.is_admin());

drop policy if exists "admin read progress" on public.student_progress;
create policy "admin read progress" on public.student_progress for select to authenticated
using (public.is_admin());

grant execute on function public.join_group_by_code(text) to authenticated;
grant execute on function public.record_attempt(text,text,text,text,boolean,integer) to authenticated;
grant execute on function public.is_teacher_of_group(uuid) to authenticated;
grant execute on function public.is_member_of_group(uuid) to authenticated;
grant execute on function public.is_admin() to authenticated;

-- Tabla de posiciones de un grupo (nombre + XP total). Solo puede consultarla
-- alguien que sea alumno o docente de ese grupo (o admin). No expone las
-- filas crudas de student_progress, solo el total agregado por alumno.
create or replace function public.group_leaderboard(p_group_id uuid)
returns table(student_id uuid, full_name text, xp bigint)
language plpgsql
security definer
set search_path = public
stable
as $$
begin
  if not (
    public.is_member_of_group(p_group_id)
    or public.is_teacher_of_group(p_group_id)
    or public.is_admin()
  ) then
    raise exception 'No autorizado.';
  end if;

  return query
    select p.id, p.full_name, coalesce(sum(sp.xp),0)::bigint
    from public.group_members gm
    join public.profiles p on p.id = gm.student_id
    left join public.student_progress sp on sp.student_id = p.id
    where gm.group_id = p_group_id
    group by p.id, p.full_name
    order by 3 desc;
end;
$$;

grant execute on function public.group_leaderboard(uuid) to authenticated;

-- IMPORTANTE:
-- Por seguridad, el registro web siempre crea alumnos.
-- Un administrador puede cambiar el rol de cualquier cuenta desde el panel
-- admin de la app. Para la primera cuenta admin (no hay otra forma de crear
-- la primera), ejecuta manualmente en SQL Editor:
-- update public.profiles set role='admin' where username='<usuario>';
